apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- database.yaml
- messages.yaml
- elastic.yaml
- manufacturing.yaml
- planning.yaml
- api.yaml

namespace: observability
images:
- name: api
  newName: binesty.azurecr.io/api
  newTag: e96b0b7d36f802c14218916d113bf8c444b115fa
- name: manufacturing
  newName: binesty.azurecr.io/manufacturing
  newTag: e96b0b7d36f802c14218916d113bf8c444b115fa
- name: planning
  newName: binesty.azurecr.io/planning
  newTag: e96b0b7d36f802c14218916d113bf8c444b115fa
